import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '友情链接',
		desc: '',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '梦爱吃鱼',
				sitenick: '',
				title: '梦爱吃鱼',
				desc: '不负心灵，不负今生。',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: getFavicon('blog.bsgun.cn'),
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: ['Nuxt'],
				date: '2025-08-17',
				comment: '',
			},
			{
				author: 'Pinpe',
				sitenick: '云端',
				title: 'Pinpe的云端',
				desc: '一个属于自己的云朵。',
				link: 'https://pinpe.top/',
				feed: 'https://pinpe.top/rss.xml',
				icon: 'https://pinpe.top/favicon/logo.png', // expected
				avatar: 'https://pinpe.top/head.jpg',
				archs: ['Astro', 'Vercel'],
				date: '2024-10-31',
				comment: '学生，奇妙幻想和思考。',
			},
			{
				author: '水氵冫',
				sitenick: '微霞',
				desc: '水风清，晚霞明',
				link: 'https://yuuu.org/',
				feed: 'https://yuuu.org/atom.xml',
				icon: 'https://cdn.yuuu.org/img/favicon-32x32.png',
				avatar: 'https://cdn.yuuu.org/img/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-11-03',
				comment: '学生，技术分享，生活。',
			},
			{
				author: 'Tianli',
				desc: '自知之明是最可贵的知识！',
				link: 'https://blog.tianli0.top/',
				feed: 'https://blog.tianli0.top/rss.xml',
				icon: getGhIcon('tianli0'),
				avatar: getGhAvatar('tianli0'),
				archs: ['VitePress', '国内 CDN'],
				date: '2024-12-04',
				comment: '技术学习笔记，TianliGPT开发者。',
			},
			{
				author: '花生莲子粥',
				desc: '与世无争，不染于泥',
				link: 'https://blog.hslzz.cn/',
				icon: 'https://blog.hslzz.cn/favicon.ico',
				avatar: 'https://blog.hslzz.cn/img/avatar.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2025-01-03',
				comment: 'Linux系统配置、服务部署、Hexo优化等技术教程，',
			},
			{
				author: '伍十七',
				sitenick: 'everfu',
				desc: '你好👋，我是伍十七，一个三流编程狮。',
				link: 'https://www.efu.me/',
				icon: 'https://www.efu.me/favicon.ico',
				avatar: getGhAvatar('everfu'),
				archs: ['Next.js', '国内 CDN'],
				date: '2025-01-12',
				comment: 'Hexo Solitude 主题作者，经常换自己网站。',
			},
			{
				author: '鸢栀',
				sitenick: '仓库',
				title: '鸢栀的仓库',
				desc: '每天写下自己的喜欢',
				link: 'https://yuazhi.cn/',
				icon: 'https://yuazhi.cn/yuazhi.ico',
				avatar: 'https://weavatar.com/avatar/1dc444f85a6673099a47170588bbc6d7?s=96',
				archs: ['HTML', '服务器'],
				date: '2025-02-12',
				comment: '日常、前端、福瑞。',
			},
			{
				author: '阿呆',
				title: '阿呆的博客',
				desc: '分享，学习有趣的知识',
				link: 'https://adaiblog.github.io/',
				feed: 'https://adaiblog.github.io/atom.xml',
				icon: 'https://adaiblog.github.io/favicon.ico', // expected
				avatar: 'https://adaiblog.github.io/img/adai.png',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-11',
				comment: '技术分享与生活。',
			},
			{
				author: '葱苓',
				sitenick: '语畔',
				title: '葱苓语畔',
				desc: 'Don\'t worry, be happy.',
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/feed.xml',
				icon: 'https://blog.ciraos.top/favicon.ico',
				avatar: getGhAvatar('ciraos'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-03-28',
				comment: '前端学习。',
			},
			{
				author: '懋和道人',
				desc: '李懋和，俗名李栋梁。书法、国画爱好者，互联网安全与前端建设者。',
				link: 'https://www.dao.js.cn/',
				feed: 'https://www.dao.js.cn/feed.php',
				icon: 'https://www.dao.js.cn/zb_users/upload/2024/09/202409191726720024363275.png',
				avatar: getQqAvatar('466660026'),
				archs: ['PHP', '国内 CDN'],
				date: '2025-04-14',
				comment: '懋和道人，聚焦网站建设与技术，弘扬传统文化。',
			},
			{
				author: 'iFluxArt',
				desc: '斐启智境 · 流韵新生',
				link: 'https://www.iflux.art/',
				icon: 'https://www.iflux.art/favicon.ico',
				avatar: 'https://www.iflux.art/favicon.ico',
				archs: ['Next.js', 'Vercel'],
				date: '2025-04-16',
				comment: '文档型知识库，含AIGC、开发、设计、运营、传媒、工具等内容。',
			},
			{
				author: 'ZL Asica',
				title: 'ZLA 小站',
				desc: '月亮不抱你，星星会落在你怀里✨🌙',
				link: 'https://zla.pub/',
				feed: 'https://zla.pub/feed.xml',
				icon: getGhIcon('ZL-Asica'),
				avatar: getGhAvatar('ZL-Asica'),
				archs: ['Next.js', 'Vercel'],
				date: '2025-04-29',
				comment: '机器学习、前端开发、旅游经历。',
			},
			{
				author: '竹林里有冰',
				title: '竹林里有冰的博客',
				desc: '仍然在划水的菜鸡',
				link: 'https://zhul.in/',
				feed: 'https://zhul.in/rss.xml',
				icon: 'https://zhul.in/favicon.ico',
				avatar: 'https://static.031130.xyz/avatar.webp',
				archs: ['Hexo', '服务器'],
				date: '2025-05-03',
				comment: '前端开发、网络配置、服务器运维及开源工具实战经验。',
			},
			{
				author: '东方月初',
				sitenick: 'BiuXin',
				title: 'BiuXin-s Blog',
				desc: '人生的每一天，都在学习当中',
				link: 'https://zhilu.biuxin.com/',
				feed: 'https://zhilu.biuxin.com/atom.xml',
				icon: 'https://x.xinb.de/i/2024/09/19/040857.webp',
				avatar: getGhAvatar('damizai'),
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-05-09',
				comment: '软件工具资源，博客部署美化。',
			},
			{
				author: 'shenley',
				sitenick: '存档点',
				title: 'shenley的存档点',
				desc: '随手存个档～',
				link: 'https://blog.shenley.cn/',
				feed: 'https://blog.shenley.cn/atom.xml',
				icon: 'https://blog.shenley.cn/avatar.jpg',
				avatar: 'https://blog.shenley.cn/avatar.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-05-20',
				comment: '前端开发、生活分享。',
			},
			{
				author: '大马数字生活',
				title: '大马数字生活-digital life my',
				desc: '本部落格是一个专门分享生活在马来西亚，有关数字生活的内容包含：生活方式 个人经历 使用体验 评测分析 数码产品 分享内容 海外消费 海外通讯等内容。',
				link: 'https://digitallife.my/',
				feed: 'https://digitallife.my/feed/',
				icon: 'https://digitallife.my/favicon.ico',
				avatar: 'https://digitallife.my/wp-content/uploads/2025/06/cropped-1751133864-bloglogo.jpg',
				archs: ['WordPress', 'Cloudflare'],
				date: '2025-06-29',
				comment: '大马数字生活及相关海外账户等事宜。',
			},
			{
				author: '路狐羽',
				sitenick: '羽音',
				title: '羽音 × Seraphonogram',
				desc: '一只毛茸茸的博客',
				link: 'https://blog.navifox.net/',
				icon: 'https://blog.navifox.net/favicon.ico',
				avatar: 'https://blog.navifox.net/favicon.ico',
				archs: ['VitePress', '服务器'],
				date: '2025-07-14',
				comment: 'Python、Django 等编程知识、开发工具使用及算法题解等内容。',
			},
			{
				author: '月空人',
				desc: '偶尔写些博客，发发牢骚',
				link: 'https://whbbit.cn/',
				feed: 'https://whbbit.cn/atom.xml',
				icon: 'https://whbbit.cn/favicon.ico',
				avatar: 'https://bitmc.uno/picgo/126662463_p2.jpg',
				archs: ['Nuxt', '服务器'],
				date: '2025-07-28',
				comment: '分享 Vue、Nuxt 等前端技术的使用技巧、版本特性、工具集成及相关翻译文章。',
			},
			{
				author: 'Teror Fox',
				sitenick: '客栈',
				title: 'Teror的客栈',
				desc: '欢迎光临～',
				link: 'https://blog.trfox.top/',
				feed: 'https://blog.trfox.top/atom.xml',
				icon: 'https://blog.trfox.top/favicon.ico',
				avatar: 'https://img.trfox.top/assets/avatar.jpg',
				archs: ['Mix Space', 'Vercel'],
				date: '2025-08-03',
				comment: '技术相关的木马免杀测试、服务器处理与迁移、工具美化，以及个人博客系统更新、回归记录等。',
			},
			{
				author: '落憾',
				sitenick: 'EnLtLH',
				title: '落憾',
				desc: '建此博客，以示吾思。话天篆地，自由吾心。',
				link: 'https://blog.enltlh.me/',
				feed: 'https://blog.enltlh.me/atom.xml',
				icon: 'https://cdn2.enltlh.me/pichub/1/2025/19e0fab452a27b75.png',
				avatar: 'https://cdn2.enltlh.me/pichub/1/2025/2231d2da22a739df.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-17',
				comment: '',
			},
			{
				author: 'AirTouch',
				desc: '分享技术、生活、思考。',
				link: 'https://www.xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://www.xsl.im/favicon.webp',
				avatar: 'https://www.xsl.im/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2025-08-18',
				comment: '网站反代配置、服务器评测、域名更换、存储加速、工具推荐、编程题解等折腾与技术分享。',
			},
			{
				author: '青序栈',
				desc: '青序成栈·向简而生',
				link: 'https://qxzhan.cn/',
				feed: 'https://qxzhan.cn/feed/',
				icon: 'https://qxzhan.cn/favicon.png',
				avatar: 'https://qxzhan.cn/favicon.png',
				archs: ['Typecho', '国内 CDN'],
				date: '2025-08-20',
				comment: '网站攻击处理曝光，博客配置魔改等技术教程与资源分享。',
			},
			{
				author: 'Snowykami',
				sitenick: '空间站',
				title: '粒子空间站',
				desc: '轻思若水，雪化生香',
				link: 'https://blog.sfkm.me/',
				feed: 'https://blog.sfkm.me/feed.xml',
				icon: getQqAvatar('2751454815', QqAvatarSize.Size100),
				avatar: getQqAvatar('2751454815'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-08-25',
				comment: '云原生、HomeLab 搭建、网络安全、容器化、静态网站托管等领域的技术实践。',
			},
			{
				author: 'Restent Ou',
				title: 'Restent\'s Notebook',
				desc: 'Secret with Silent.',
				link: 'https://blog.gxres.net/',
				feed: 'https://blog.gxres.net/atom.xml',
				icon: 'https://library.gxres.net/images/icons/favicon.webp',
				avatar: 'https://library.gxres.net/images/avatars/gxres042.webp',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-08-28',
				comment: '前端/网络技术实践与个人记录',
			},
			{
				author: '酥米',
				title: '酥米的小站',
				desc: '终有一日，寻梦中人',
				link: 'https://www.sumi233.top/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://www.sumi233.top/favicon.ico',
				avatar: 'https://cdn.sumi233.top/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/userfb6a1018b84ce485.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2025-08-29',
				comment: '计算机网络知识，设备折腾。',
			},
			{
				author: 'kzhik',
				title: 'kzhik\'s website',
				desc: '前端/网络技术实践与个人记录',
				link: 'https://www.kzhik.cn/',
				feed: 'https://www.kzhik.cn/resources/rss.xml',
				icon: 'https://www.kzhik.cn/favicon.ico',
				avatar: 'https://www.kzhik.cn/avatar.webp',
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-08-31',
				comment: '前端/网络技术实践与个人记录',
			},
			{
				author: 'ATao',
				title: 'ATao-Blog',
				desc: '做自己喜欢的事',
				link: 'https://blog.atao.cyou',
				feed: 'https://blog.atao.cyou/atom.xml',
				icon: 'https://cdn.atao.cyou/Web/Avatar.png',
				avatar: 'https://cdn.atao.cyou/Web/Avatar.png',
				archs: ['Nuxt', '服务器'],
				date: '2025-09-09',
				comment: '技术实践与问题解决方案',
			},
			{
				author: '克喵',
				sitenick: '喵落阁',
				title: '喵落阁',
				desc: '愿你看清一切真相后，依旧热爱你的家人和朋友。',
				link: 'https://blog-v3.kemeow.top/',
				feed: 'https://blog-v3.kemeow.top/atom.xml',
				icon: 'https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp',
				avatar: 'https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-09-11',
				comment: '博客折腾记录、工具/资源网站收集。',
			},
			{
				author: 'fishcpy',
				sitenick: '小破站',
				title: 'fishcpy的小破站',
				desc: '非淡泊无以明志，非宁静无以致远',
				link: 'https://blog.fis.ink/',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://www.fis.ink/img/logo_c.png',
				avatar: 'https://www.fis.ink/img/logo.png',
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-09-13',
				comment: '博客/服务器技术实践、生活记录、资源分享。',
			},
			{
				author: '鲲',
				title: 'KUN\'s Blog',
				desc: 'KUN\'s moe blog, KUN IS THE CUTEST!',
				link: 'https://soft.moe/',
				feed: 'https://soft.moe/atom.xml',
				icon: 'https://soft.moe/favicon.ico',
				avatar: 'https://soft.moe/avatar.webp',
				archs: ['VitePress', 'Cloudflare'],
				date: '2025-09-13',
				comment: '鲲Gal站长，Nuxt高手，重构博客计划已搁置两年有余。',
			},
			{
				author: 'Refactored',
				title: 'RefactX Project',
				desc: '形体是简单而纯粹的，它不是完整的群体，每个形体都指向其复杂性，并最终被复杂性联系在一起。',
				link: 'https://www.refact.cc/',
				feed: 'https://www.refact.cc/rss.xml',
				icon: 'https://www.refact.cc/favicon.ico',
				avatar: 'https://www.refact.cc/avatar.png',
				archs: ['Astro', 'Vercel'],
				date: '2025-09-22',
				comment: 'RefactX 主题相关介绍、个人思考。',
			},
			{
				author: 'Elykia',
				title: '致以无暇之人',
				desc: '爱莉希雅永远爱你～',
				link: 'https://blog.elykia.cn/',
				feed: 'https://blog.elykia.cn/atom.xml',
				icon: 'https://blog.elykia.cn/favicon.ico',
				avatar: getGhAvatar('elykia-cn'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-09-26',
				comment: 'Hexo 安知鱼主题美化。',
			},
			{
				author: 'VnYzm',
				title: 'VnYzm的博客',
				desc: '分享技术心得和摸鱼感想',
				link: 'https://vnyzm.top/',
				icon: 'https://vnyzm.top/img/favicon.ico',
				avatar: 'https://vnyzm.top/img/profile.jpg',
				archs: ['Python', 'GitHub Pages'],
				date: '2025-10-01',
				comment: '动漫观后感、游戏玩后感、技术笔记。',
			},
			{
				author: '七十二时.',
				desc: '咸鱼发呆时刻。一条咸鱼的发呆据点，也是我的实验日志。',
				link: 'https://www.qsesvick.top/',
				feed: 'https://www.qsesvick.top/feed/',
				icon: getFavicon('qsesvick.top'),
				avatar: 'https://files3.qsesvick.top/JCZY/LOGO/YJQSES.png',
				archs: ['WordPress', 'Cloudflare'],
				date: '2025-10-05',
				comment: '工具分享，博客折腾。',
			},
			{
				author: 'Sakun',
				sitenick: 'Notebook',
				title: 'Sakun Notebook',
				desc: 'Sakun Notebook',
				link: 'https://www.sakun.space/',
				feed: 'https://www.sakun.space/atom.xml',
				icon: 'https://www.sakun.space/images/favicon-32x32-next.png',
				avatar: 'https://www.sakun.space/images/avatar.png',
				archs: ['Hexo', '服务器'],
				date: '2025-10-07',
				comment: '动漫评论。',
			},
			{
				author: 'XUIOO',
				desc: '一叶障目，不见泰山；两耳塞豆，不闻雷霆。',
				link: 'https://blog.xuioo.com/',
				feed: 'https://blog.xuioo.com/rss.xml',
				icon: 'https://r2.blog.xuioo.com/GED15E4G5A1F52A1F51A.png',
				avatar: 'https://blog.xuioo.com/27c69590279fdc3be2cd7c901e3d07ad.jpg',
				archs: ['Astro', '国内 CDN'],
				date: '2025-10-08',
				comment: '博客折腾。',
			},
			{
				author: '伏枥',
				sitenick: '伏枥之间',
				desc: '莫听穿林打叶声，何妨吟啸且徐行。',
				link: 'https://www.leehenry.top/',
				feed: 'https://www.leehenry.top/rss.xml',
				icon: 'https://www.leehenry.top/favicon/leaf-solid.svg',
				avatar: 'https://leehenry.top/friends/my-avatar-portrait.jpg',
				archs: ['Astro', '服务器'],
				date: '2025-10-15',
				comment: '生活分享、社会思考与技术探索。',
			},
			{
				author: '栖童',
				sitenick: 'の小站',
				title: '栖童の小站',
				desc: '越努力,越幸运',
				link: 'https://blog.linux-qitong.top/',
				feed: 'https://blog.linux-qitong.top/atom.xml',
				icon: 'https://blog.linux-qitong.top/img/favicon.webp',
				avatar: 'https://blog.linux-qitong.top/img/avatar.webp',
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-10-17',
				comment: '原名青稚，博客记录Linux使用、博客部署、生活反思。',
			},
			{
				author: 'Dejavu',
				title: 'Dejavu\'s Blog',
				link: 'https://blog.dejavu.moe/',
				feed: 'https://blog.dejavu.moe/index.xml',
				icon: 'https://blog.dejavu.moe/favicon.ico',
				avatar: 'https://blog.dejavu.moe/avatar.webp',
				archs: ['Hugo', 'Cloudflare'],
				date: '2025-10-23',
				comment: '记录技术、生活、思考。',
			},
			{
				author: '墨韵先知',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://www.htmacg.cn/',
				feed: 'https://www.htmacg.cn/feed',
				icon: 'https://www.htmacg.cn/wp-content/uploads/2025/09/cropped-RC-LOGO_icon-32x32.png',
				avatar: 'https://www.htmacg.cn/wp-content/uploads/2025/08/cropped-user.png',
				archs: ['WordPress', '国内 CDN'],
				date: '2025-10-27',
				comment: '原名胡桃木实验室，具有运维/系统等技术分享。',
			},
			{
				author: '广树',
				sitenick: '维基萌',
				desc: '萌即是正义！时不时分享一些ACG活动记录与有趣代码的小站！',
				link: 'https://www.wikimoe.com/',
				feed: 'https://www.wikimoe.com/rss/blog',
				icon: 'https://www.wikimoe.com/upload/siteImg/siteFavicon.png',
				avatar: 'https://www.wikimoe.com/upload/avatar/65994c0f3af05a21862459e9.webp',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-10-30',
				comment: '游戏数据/圣地巡礼/代码笔记。',
			},
			{
				author: 'imlonghao',
				desc: '非专业人士的非专业博客',
				link: 'https://imlonghao.com/',
				feed: 'https://imlonghao.com/feed.xml',
				icon: 'https://imlonghao.com/favicon.ico',
				avatar: 'https://imlonghao.com/favicon.ico',
				archs: ['Python', 'Cloudflare'],
				date: '2025-10-31',
				comment: '网络安全与实践。',
			},
			{
				author: '灯火不休时',
				desc: '所爱隔山海，山海不可平；所念皆星河，星河不可及',
				link: 'https://blog.dhbxs.top/',
				feed: 'https://blog.dhbxs.top/feed.xml',
				icon: 'https://file.dhbxs.top/favicon.ico',
				avatar: 'https://file.dhbxs.top/favicon.ico',
				archs: ['Halo', '国内 CDN'],
				date: '2025-11-01',
				comment: '深度学习、大数据与软件工程学习笔记。',
			},
		],
	},
	/* ========从此处新增友链======== */
	{
		name: '现实之域',
		desc: '博主们或许正忙着追随生活的烟火气。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '恩泽',
				sitenick: 'Colsrch',
				title: 'Colsrch的小破站',
				desc: '愿多年以后，我可以酌一杯清酒，烂醉如泥，梦中回到我们的曾经。',
				link: 'https://colsrch.cn/',
				feed: 'https://colsrch.cn/atom.xml',
				icon: getFavicon('colsrch.cn'),
				avatar: 'https://7.isyangs.cn/1/657976c27bea6-1.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-01',
				comment: '鸽王，去哪里发展了？',
			},
			{
				author: '小李同学',
				sitenick: 'Coding',
				title: '小李同学 Coding',
				desc: '一支努力变强的小彩笔',
				link: 'https://blog.xxfer.cn/',
				feed: 'https://blog.xxfer.cn/rss.xml',
				icon: getFavicon('blog.xxfer.cn'),
				avatar: getGhAvatar('JJLibra'),
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-01',
				comment: '瓜大网安学长。',
			},
			{
				author: '桜紺狸',
				sitenick: '部落阁',
				title: '桜紺狸の部落阁',
				desc: '一个闲聊萌新动漫技术交流站',
				link: 'https://www.skira.top/',
				feed: 'https://www.skira.top/feed.xml',
				icon: 'https://www.skira.top/img/skira.ico',
				avatar: 'https://www.skira.top/img/lemonsuka.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-02-01',
				comment: '搞机发烧友，小众系统爱好者，前端研究员。',
			},
			{
				author: '茂茂物语',
				desc: '茂茂的成长之路，包含前端常用知识、源码阅读笔记、各种奇淫技巧、日常提效工具等',
				link: 'https://notes.fe-mm.com/',
				icon: getGhIcon('maomao1996'),
				avatar: getGhAvatar('maomao1996'),
				archs: ['VitePress', 'Cloudflare'],
				date: '2024-02-17',
			},
			{
				author: 'Naokuo',
				desc: '请给我来亿碗三鲜面',
				link: 'https://index.naokuo.top/',
				feed: 'https://index.naokuo.top/rss2.xml',
				icon: getFavicon('index.naokuo.top'),
				avatar: 'https://yl2209.github.io/img/favicon.ico',
				archs: ['Hexo', '服务器'],
				date: '2025-08-18',
				comment: '',
			},
			{
				author: '间窗',
				sitenick: '',
				title: '间窗的博客',
				desc: '窗外是蓝天白云，心里是小杏扉间。',
				link: 'https://www.jcblog.com.cn',
				feed: 'https://www.jcblog.com.cn/feed.xml',
				icon: getFavicon('jcblog.com.cn'),
				avatar: getGhAvatar('DohhhDo'),
				archs: [],
				date: '2025-08-22',
				comment: '',
			},
			{
				author: '尘',
				sitenick: '',
				title: '尘の个人博客',
				desc: '一个高中生 UP 搭的博客 QwQ',
				link: 'https://blog.mcxiaochen.top/',
				feed: '',
				icon: getFavicon('blog.mcxiaochen.top'),
				avatar: 'https://blog.mcxiaochen.top/favicon.ico',
				archs: ['Hexo', 'Netlify'],
				date: '2025-08-22',
				comment: '',
			},
			{
				author: 'H2O',
				sitenick: '',
				title: 'THW’s Blog',
				desc: 'Live a good life meet slowly',
				link: 'https://thw.lol',
				feed: '',
				icon: getFavicon('thw.lol'),
				avatar: 'https://img.dooki.cloud/i/2025/08/29/68b09e116c4b6.webp',
				archs: ['Astro', 'Netlify'],
				date: '2025-08-24',
				comment: '',
			},
			{
				author: '落尘up',
				sitenick: '',
				title: '落尘up',
				desc: '愿你我都做,生活的高手。',
				link: 'https://www.luochen.chat/',
				feed: 'https://www.luochen.chat/atom.xml',
				icon: getFavicon('www.luochen.chat'),
				avatar: 'https://www.luochenup.xyz/b_a5a3aa888355bdc617dca021efb19ab8.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-30',
				comment: '',
			},
			{
				author: '临明小狐狸',
				sitenick: '',
				title: '临明小狐狸の小窝',
				desc: 'Ciallo～(∠・ω< )⌒★',
				link: 'https://lmxhl.top',
				feed: '',
				icon: getFavicon('lmxhl.top'),
				avatar: 'https://lmxhl.top/wp-content/uploads/2025/08/cropped-g.jpg',
				archs: ['Astro', 'Cloudflare'],
				date: '2025-10-24',
				comment: '',
			},
		],
	},
] satisfies FeedGroup[]
