import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar } from './utils/img'

export default [
	// #region 相谈甚多
	{
		name: '友情链接',
		desc: '',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '梦爱吃鱼',
				sitenick: '',
				title: '梦爱吃鱼',
				desc: '不负心灵，不负今生。',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: getFavicon('blog.bsgun.cn'),
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: ['Nuxt'],
				date: '2025-08-17',
				comment: '',
			},
			{
				author: '纸鹿本鹿',
				sitenick: '',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: getFavicon('blog.zhilu.site'),
				avatar: 'https://www.zhilu.site/api/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-17',
				comment: '',
			},
			{
				author: 'Mo的记事簿',
				sitenick: '',
				title: 'Mo的记事簿',
				desc: '万年鸽王，哈哈OvO',
				link: 'https://blog.xiowo.net/',
				feed: 'https://blog.xiowo.net/atom.xml',
				icon: getFavicon('blog.xiowo.net'),
				avatar: 'https://blog.xiowo.net/img/avatar.png',
				archs: ['Hexo', '服务器'],
				date: '2025-08-18',
				comment: '',
			},
			{
				author: '清羽飞扬',
				sitenick: '',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: getFavicon('blog.liushen.fun'),
				avatar: 'https://blog.liushen.fun/info/avatar.ico',
				archs: ['Hexo', '服务器'],
				date: '2025-08-18',
				comment: '',
			},
			{
				author: '间窗',
				sitenick: '',
				title: '间窗的博客',
				desc: '窗外是蓝天白云，心里是小杏扉间。',
				link: 'https://www.jcblog.com.cn',
				feed: 'https://www.jcblog.com.cn/feed.xml',
				icon: getFavicon('jcblog.com.cn'),
				avatar: getGhAvatar('DohhhDo'),
				archs: [],
				date: '2025-08-22',
				comment: '',
			},
			{
				author: '尘',
				sitenick: '',
				title: '尘の个人博客',
				desc: '一个高中生 UP 搭的博客 QwQ',
				link: 'https://blog.mcxiaochen.top/',
				feed: '',
				icon: getFavicon('blog.mcxiaochen.top'),
				avatar: 'https://blog.mcxiaochen.top/favicon.ico',
				archs: ['Hexo', 'Netlify'],
				date: '2025-08-22',
				comment: '',
			},
			{
				author: 'H2O',
				sitenick: '',
				title: 'THW’s Blog',
				desc: '前途似海，来日方长',
				link: 'https://tianhw.top/',
				feed: 'https://tianhw.top/rss.xml',
				icon: getFavicon('tianhw.top'),
				avatar: 'https://image.tianhw.top/avatar.webp',
				archs: ['Astro', 'Netlify'],
				date: '2025-08-24',
				comment: '',
			},
			{
				author: '落尘up',
				sitenick: '',
				title: '落尘up',
				desc: '愿你我都做,生活的高手。',
				link: 'https://www.luochen.chat/',
				feed: 'https://www.luochen.chat/atom.xml',
				icon: getFavicon('www.luochen.chat'),
				avatar: 'https://www.luochenup.xyz/b_a5a3aa888355bdc617dca021efb19ab8.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-30',
				comment: '',
			},
			{
				author: '临明小狐狸',
				sitenick: '',
				title: '临明小狐狸の小窝',
				desc: 'Ciallo～(∠・ω< )⌒★',
				link: 'https://lmxhl.top',
				feed: '',
				icon: getFavicon('lmxhl.top'),
				avatar: 'https://lmxhl.top/wp-content/uploads/2025/08/cropped-g.jpg',
				archs: ['Astro', 'Cloudflare'],
				date: '2025-10-24',
				comment: '',
			},
			{
				author: 'MaxQi',
				sitenick: '',
				title: 'MaxQi的说说',
				desc: '一名高中生的技术与成长记录',
				link: 'https://maxqi.top/',
				feed: 'https://maxqi.top/feed/',
				icon: getFavicon('maxqi.top'),
				avatar: 'https://p.maxqi.top/img/2025/10/01/68dce7326320a.png',
				archs: ['Typecho', 'Cloudflare'],
				date: '2025-10-24',
				comment: '',
			},
		],
	},
] satisfies FeedGroup[]
